### ISSUE TITLE
Kebab-case class names are not converted to CamelCase

### ISSUE THREAD

**Issue by papermana** [netguru/create-react-app#5]
### Can you reproduce the problem with latest npm?

Yes.

### Description

If I define a kebab-case class in an `.scss` file, it should get converted to a CamelCase automatically. This does not currently happen.

### Expected behavior

If I create a stylesheet with
```
.foo-bar { ... }
```
in it, and then import it in my `.js` file, I should get an object like
```
{
  fooBar: 'someHashedClassName',
}
```

### Actual behavior
When imported, 
```
.foo-bar { ... }
```
returns a file like this:
```
{
  'foo-bar': 'someHashedClassName',
}
```

### Environment

Node: v8.2.1
NPM: 5.3.0
MacOS 10.12.6

**Comment by paweljedrzejczyk** [comment]
Will do. `camelCase` option in: https://github.com/webpack-contrib/css-loader#options

**Comment by paweljedrzejczyk** [comment]
Added in latest version (1.0.2) of netguru-react-scripts.
Upgrade the package: `yarn upgrade netguru-react-scripts`
