### ISSUE TITLE
Unable to mock document.createRange with setupTests.js

### ISSUE THREAD

**Issue by RusinovAnton** [netguru/create-react-app#54]
My tests are failing in CI because of following error.
```

TypeError: document.createRange is not a function

    at findCommonOffsetParent (/app/node_modules/popper.js/dist/umd/popper.js:259:24)

    at getReferenceOffsets (/app/node_modules/popper.js/dist/umd/popper.js:744:83)

    at Popper.update (/app/node_modules/popper.js/dist/umd/popper.js:918:28)

    at Popper.update$$1 (/app/node_modules/popper.js/dist/umd/popper.js:2466:21)

    at /app/node_modules/popper.js/dist/umd/popper.js:51:7

    at <anonymous>

 DEBUG [7c086cee] 	
```
I've tried to mock this function globally by adding `src/setupTests.js` like documentation of CRA suggests:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#initializing-test-environment

But that wasn't efficient - they're still failing

**Comment by papermana** [comment]
Hm, what does your `src/setupTests.js` look like?

There was a discussion about this problem in the Popper repo and someone had a [solution](https://github.com/FezVrasta/popper.js/issues/478#issuecomment-407422016) that supposedly works.

**Comment by RusinovAnton** [comment]
I did take that snippet excluding enzyme adapter since I do not use enzyme at all

**Comment by RusinovAnton** [comment]
https://github.com/NodusMedical/nodus-frontend/pull/65/files

**Comment by RusinovAnton** [comment]
I've tried to make test of setupTests.js and added next code there

```
document.RAWR = 'test';
```

and then tried to access it in one of my tests like
```
typeof document.RAWR
```

And it said that RAWR is undefined

**Comment by papermana** [comment]
There's a typo there.
```
"setupFiles": ["./setup.test.js"]
```
But the actual file is `setupTests.js`.

**Comment by RusinovAnton** [comment]
The issue was with invalid Circle CI configuration. 
I was using "prebuild" script to run "yarn test" command.
 Now changed it for Circle CI job and problem is gone. 

Sorry for false issue
